# Generated by Django 4.2.25 on 2025-10-22 13:30

import apps.tasks_app.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(default='Задача LU', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'В очікуванні'), ('queued', 'В черзі'), ('running', 'Виконується'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('matrix_file', models.FileField(blank=True, help_text='Файл з матрицею A', null=True, upload_to=apps.tasks_app.models.task_upload_path)),
                ('vector_file', models.FileField(blank=True, help_text='Файл з вектором b', null=True, upload_to=apps.tasks_app.models.task_upload_path)),
                ('matrix_size', models.IntegerField(blank=True, help_text='Розмірність матриці (N)', null=True)),
                ('max_n', models.IntegerField(default=5000, help_text='Макс. допустимий розмір N')),
                ('save_matrices', models.BooleanField(default=False, help_text='Зберегти L, U, P матриці?')),
                ('result_file', models.FileField(blank=True, help_text='Файл з результатом (вектор X)', null=True, upload_to=apps.tasks_app.models.task_upload_path)),
                ('result_message', models.TextField(blank=True, help_text='Повідомлення про помилку або успіх', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='tasks_app.task')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks_app.task')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
